---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  This templete creates Kitten Carousel App on EC2 instance.
  It also create a security group allowing HTTP (Port 80) and 
  SSH (22) connections from anywhere

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Enable HTTP for Apache Web Server
        SecurityGroupIngress: 
          -   CidrIp: 0.0.0.0/0
              FromPort: 80
              IpProtocol: tcp
              ToPort: 80
          -   CidrIp: 0.0.0.0/0
              FromPort: 22
              IpProtocol: tcp
              ToPort: 22
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:  !Ref ImageId
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds: 
        - !Ref WebServerSecurityGroup
      Tags: 
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName} Stack
      UserData:
          Fn::Base64: |
            #! /bin/bash
            yum update -y
            yum install httpd -y
            FOLDER="https://raw.githubusercontent.com/akoleoglu/aws-projects/master/project-1-CF-EC2-SG-Static-Web/v2/static-web/"
            curl -s --create-dirs -o "/var/www/html/index.html" -L  "$FOLDER"index.html
            curl -s --create-dirs -o "/var/www/html/cat0.jpg" -L  "$FOLDER"cat0.jpg
            curl -s --create-dirs -o "/var/www/html/cat1.jpg" -L  "$FOLDER"cat1.jpg
            curl -s --create-dirs -o "/var/www/html/cat2.jpg" -L  "$FOLDER"cat2.jpg
            systemctl start httpd
            systemctl enable httpd
Outputs:
  WebsiteURL:
    Description: Kitten Carousel Application URL
    Value: !Sub
        - http://${PublicAddress}
        - PublicAddress: !GetAtt WebServerInstance.PublicDnsName

