AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for Roman Numerals Application
Resources:
  WebServerSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable HTTP for the WEB-APP #required
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
  WebServer:
    Type: "AWS::EC2::Instance"
    Properties:
      
      ImageId: 
      InstanceType: t2.micro
      
      KeyName: String
      
      SecurityGroupIds:
        - !Ref WebServerSG
      UserData:
        !Base64  |
          #! /bin/bash
          yum update -y
          yum install python3 -y
          pip3 install flask
          
      Tags:
        - Key: Name
          Value: Web Server of Roman Numerals App  
Outputs: